name: integration-tests
on: [pull_request]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls
